robot_NQJ=6
robot_NJ=6
robot_name="S6RPRRRP8"
robot_NL=7
robot_NKP=9
robot_KP="a2 a3 a4 a5 a6 d1 d3 d4 d5"
robot_kinconstr_exist=0
robot_NKCP=0
robot_KCP=""
robot_NMPVFIXB=31
robot_NMPVFLOATB=NOTDEFINED
