robot_NQJ=4
robot_NJ=4
robot_name="S4PRRP6"
robot_NL=5
robot_gVec=1,1,1
robot_NKP=6
robot_KP="a2 a3 a4 d2 d3 theta1"
robot_kinconstr_exist=0
robot_NKCP=0
robot_KCP=""
robot_NMPVFIXB=15
robot_NMPVFLOATB=NOTDEFINED
robot_NTAUJFIXBREGNN=37
