robot_NQJ=4
robot_NJ=4
robot_name="S4PRRR2"
robot_NL=5
robot_NKP=2
robot_KP="a3 a4"
robot_kinconstr_exist=0
robot_NKCP=0
robot_KCP=""
robot_NMPVFIXB=NOTDEFINED
robot_NMPVFLOATB=NOTDEFINED
robot_NTAUJFIXBREGNN=NOTDEFINED
