robot_NQJ=3
robot_NJ=3
robot_name="S3PPP1"
robot_NL=4
robot_NKP=3
robot_KP="a2 a3 theta1"
robot_kinconstr_exist=0
robot_NKCP=0
robot_KCP=""
robot_NMPVFIXB=3
robot_NMPVFLOATB=NOTDEFINED
robot_NTAUJFIXBREGNN=6
