robot_NQJ=6
robot_NJ=6
robot_name="S6PRPRRR1"
robot_NL=7
robot_NKP=12
robot_KP="a2 a3 a4 a5 a6 alpha2 d2 d4 d5 d6 theta1 theta3"
robot_kinconstr_exist=0
robot_NKCP=0
robot_KCP=""
robot_NMPVFIXB=NOTDEFINED
robot_NMPVFLOATB=NOTDEFINED
