robot_NQJ=5
robot_NJ=5
robot_name="S5RPRPP3"
robot_NL=6
robot_gVec=1,1,1
robot_NKP=7
robot_KP="a2 a3 a4 a5 d1 d3 theta2"
robot_kinconstr_exist=0
robot_NKCP=0
robot_KCP=""
robot_NMPVFIXB=NOTDEFINED
robot_NMPVFLOATB=NOTDEFINED
robot_NTAUJFIXBREGNN=NOTDEFINED
