robot_NQJ=4
robot_NJ=4
robot_name="S4RRPR1"
robot_NL=5
robot_NKP=7
robot_KP="a2 a3 a4 d1 d2 d4 theta3"
robot_kinconstr_exist=0
robot_NKCP=0
robot_KCP=""
robot_NMPVFIXB=10
robot_NMPVFLOATB=NOTDEFINED
robot_NTAUJFIXBREGNN=21
