robot_NQJ=5
robot_NJ=5
robot_name="S5RRPPR5"
robot_NL=6
robot_gVec=1,1,1
robot_NKP=8
robot_KP="a2 a3 a4 a5 d1 d2 d5 theta3"
robot_kinconstr_exist=0
robot_NKCP=0
robot_KCP=""
robot_NMPVFIXB=25
robot_NMPVFLOATB=NOTDEFINED
robot_NTAUJFIXBREGNN=68
