robot_NQJ=5
robot_NJ=5
robot_name="S5RPPPR2"
robot_NL=6
robot_NKP=9
robot_KP="a2 a3 a4 a5 d1 d5 theta2 theta3 theta4"
robot_kinconstr_exist=0
robot_NKCP=0
robot_KCP=""
robot_NMPVFIXB=NOTDEFINED
robot_NMPVFLOATB=NOTDEFINED
robot_NTAUJFIXBREGNN=NOTDEFINED
