robot_NQJ=6
robot_NJ=6
robot_name="S6RRPPRP2"
robot_NL=7
robot_NKP=9
robot_KP="a2 a3 a4 a5 a6 d1 d2 d5 theta3"
robot_kinconstr_exist=0
robot_NKCP=0
robot_KCP=""
robot_NMPVFIXB=25
robot_NMPVFLOATB=NOTDEFINED
