robot_NQJ=5
robot_NJ=5
robot_name="S5RRRRR1"
robot_NL=6
robot_NKP=6
robot_KP="a2 a3 a4 a5 d1 d5"
robot_kinconstr_exist=0
robot_NKCP=0
robot_KCP=""
robot_NMPVFIXB=31
robot_NMPVFLOATB=NOTDEFINED
robot_NTAUJFIXBREGNN=98
