robot_NQJ=6
robot_NJ=6
robot_name="S6RRRRRR10V2"
robot_NL=7
robot_NKP=6
robot_KP="a2 a3 a4 d1 d4 d6"
robot_kinconstr_exist=0
robot_NKCP=0
robot_KCP=""
robot_NMPVFIXB=38
robot_NMPVFLOATB=NOTDEFINED
robot_NTAUJFIXBREGNN=141
