robot_NQJ=4
robot_NJ=4
robot_name="S4RRRR4"
robot_NL=5
robot_gVec=1,1,1
robot_NKP=7
robot_KP="a2 a3 a4 d1 d2 d3 d4"
robot_kinconstr_exist=0
robot_NKCP=0
robot_KCP=""
robot_NMPVFIXB=24
robot_NMPVFLOATB=NOTDEFINED
robot_NTAUJFIXBREGNN=64
