robot_NQJ=4
robot_NJ=4
robot_name="S4RRRR6"
robot_NL=5
robot_gVec=1,1,1
robot_NKP=8
robot_KP="a2 a3 a4 alpha2 d1 d2 d3 d4"
robot_kinconstr_exist=0
robot_NKCP=0
robot_KCP=""
robot_NMPVFIXB=NOTDEFINED
robot_NMPVFLOATB=NOTDEFINED
robot_NTAUJFIXBREGNN=NOTDEFINED
