robot_NQJ=5
robot_NJ=5
robot_name="S5PPRPR2"
robot_NL=6
robot_NKP=8
robot_KP="a2 a3 a4 a5 d3 d5 theta1 theta2"
robot_kinconstr_exist=0
robot_NKCP=0
robot_KCP=""
robot_NMPVFIXB=NOTDEFINED
robot_NMPVFLOATB=NOTDEFINED
robot_NTAUJFIXBREGNN=NOTDEFINED
