robot_NQJ=6
robot_NJ=6
robot_name="S6RRPPRR7"
robot_NL=7
robot_NKP=10
robot_KP="a2 a3 a4 a5 a6 alpha2 d1 d2 d5 d6"
robot_kinconstr_exist=0
robot_NKCP=0
robot_KCP=""
robot_NMPVFIXB=32
robot_NMPVFLOATB=NOTDEFINED
