robot_NQJ=6
robot_NJ=6
robot_name="S6RRRRPP7"
robot_NL=7
robot_NKP=11
robot_KP="a2 a3 a4 a5 a6 alpha2 d1 d2 d3 d4 theta5"
robot_kinconstr_exist=0
robot_NKCP=0
robot_KCP=""
robot_NMPVFIXB=NOTDEFINED
robot_NMPVFLOATB=NOTDEFINED
