robot_NQJ=5
robot_NJ=5
robot_name="S5RRPRR1"
robot_NL=6
robot_NKP=4
robot_KP="a3 a4 d4 d5"
robot_kinconstr_exist=0
robot_NKCP=0
robot_KCP=""
robot_NMPVFIXB=26
robot_NMPVFLOATB=NOTDEFINED
robot_NTAUJFIXBREGNN=74
